name: Fetch tides and deploy
on:
  schedule:
    - cron: '0 7 * * *'  # Jeden Tag um 07:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create daily HTML
        run: |
          echo "Gezeiten-Seite wird automatisch aktualisiert."
          # Nichts zu tun – index.html holt Live-Daten direkt über API

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
